[package]
name = "burrow"
version = "0.1.0"
edition = "2021"

[dependencies]
burrow_derive = { path = "../burrow_derive", optional = true }

[features]
default = ["derive"]
derive = ["dep:burrow_derive"]
